In [5]:
import pandas as pd
import numpy as np
import gensim, logging
from gensim.models import Word2Vec
import nltk
nltk.download('punkt')
data= pd.read_excel('./6767test.xlsx')
newdata=data['context'].values
sentences = [nltk.word_tokenize(context) for context in newdata]
    # train model
model = Word2Vec(sentences, min_count=1,size=50)
    # summarize the loaded model
print(model)
sentences
#len(sentences) #10
#len(sentences[9]) #138

[nltk_data] Downloading package punkt to /home/garycc227/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Word2Vec(vocab=661, size=50, alpha=0.025)


[['Users',
  'interact',
  'with',
  'museum',
  'application',
  'interfaces',
  'for',
  'many',
  'reasons',
  '.',
  'There',
  'are',
  'various',
  'types',
  'of',
  'users',
  ',',
  'who',
  'want',
  'to',
  'perform',
  'various',
  'tasks',
  ',',
  'in',
  'various',
  'contexts',
  ',',
  'that',
  'can',
  'access',
  'the',
  'same',
  'Web',
  'site',
  '.',
  'Thus',
  ',',
  'it',
  'is',
  'important',
  'to',
  'have',
  'user',
  'interfaces',
  'able',
  'to',
  'adapt',
  'to',
  'these',
  'different',
  'user',
  'requirements',
  'to',
  'facilitate',
  'the',
  'accomplishment',
  'of',
  'the',
  'desired',
  'goals',
  '.',
  'Most',
  'current',
  'interfaces',
  'to',
  'museum',
  'information',
  'do',
  'not',
  'take',
  'into',
  'account',
  'this',
  'variety',
  'of',
  'types',
  'of',
  'users',
  ',',
  'thus',
  'providing',
  'interfaces',
  'that',
  'some',
  'users',
  'find',
  'confusing',
  'to',
  'achieve',
  'their',
  'goals',
  '.

In [8]:
    # summarize vocabulary
words = list(model.wv.vocab)
# print(words)
len(words)

661

In [9]:
#model.most_similar('rules')

    # access vector for one word
#print(model.wv)
model.wv
#model.most_similar('rules').to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output.csv',index = None, header=False)

    # save model
#model.save('model.bin')
    # load model
#new_model = Word2Vec.load('model.bin')
#print(new_model)

In [10]:
for a in sentences:
    vector=model.wv[a]
vector

array([[-8.64758436e-03,  2.25899951e-03, -7.36222323e-03, ...,
        -9.52525996e-04, -6.28146483e-03, -2.73038429e-04],
       [ 6.93957321e-03,  1.08648483e-02,  5.27743297e-03, ...,
         8.11022893e-03, -5.45114884e-03, -1.37128984e-04],
       [ 1.67893275e-04, -7.33428355e-03, -9.37911961e-03, ...,
        -2.56899279e-03, -6.02942379e-03, -6.31605089e-03],
       ...,
       [ 4.96364385e-03, -2.85745391e-05, -1.03867045e-02, ...,
        -2.56652734e-03,  5.51992375e-03,  7.43920333e-04],
       [ 6.93957321e-03,  1.08648483e-02,  5.27743297e-03, ...,
         8.11022893e-03, -5.45114884e-03, -1.37128984e-04],
       [-3.41618294e-03,  5.45296003e-04,  3.28858150e-03, ...,
         7.38795381e-03, -4.57955198e-03,  1.65311946e-03]], dtype=float32)

In [11]:
for i in range(0, 10):
    vectoraa=model.wv[sentences[8]]
vectoraa

#pd.DataFrame(vectoraa).to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output08.csv', header=None, index=None)
len(sentences[8])


269

In [13]:
dataS0=sentences[0]
# dataS0

In [14]:
for b in dataS0:
    vector0=model.wv[b]
vector0
#len(vector4) #138

array([-3.4161829e-03,  5.4529600e-04,  3.2885815e-03,  1.3574216e-03,
       -3.8662003e-03,  7.7964747e-03, -6.1770868e-03,  3.7876498e-03,
       -4.1586952e-03, -1.2473933e-03,  1.2857887e-03,  9.1071120e-03,
        3.9796750e-03, -1.0406369e-02, -1.8644114e-03,  9.5307576e-03,
        8.1015928e-03,  8.8754110e-04,  5.1967860e-03,  2.5842735e-03,
        1.1506831e-02, -2.4905158e-03,  4.4178073e-03, -3.7757454e-03,
       -7.2466694e-03, -8.4220022e-03,  4.9646799e-03,  7.0803273e-03,
       -5.4296963e-03,  5.6303865e-03,  7.8532519e-03, -6.7448742e-03,
        2.6464674e-03, -8.6786263e-03, -1.5779542e-03,  3.7268400e-03,
       -7.9476078e-05, -1.0437985e-02,  9.6438751e-03,  5.5811894e-03,
       -9.9913049e-03,  6.1849412e-03, -7.9924418e-03, -6.3117743e-03,
       -5.2737342e-03,  3.5723548e-03, -1.0906490e-02,  7.3879538e-03,
       -4.5795520e-03,  1.6531195e-03], dtype=float32)

In [15]:
pd.DataFrame(vector).to_csv('./output.csv', header=None, index=None)
#pd.DataFrame(model.wv).to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6|767records/output01.csv', header=None, index=None)

In [16]:
for a in words:
    vector_2=model.wv[a]
vector_2


array([-8.8588959e-03,  6.4835562e-03,  2.1713828e-03,  6.9976477e-03,
       -3.5899167e-03, -7.1220887e-03, -2.7791166e-03, -5.8569508e-03,
        2.2560756e-03,  9.9243606e-03, -5.8932076e-03, -2.4330923e-03,
        9.8150910e-04,  4.1308566e-03, -8.7160897e-03, -8.9347688e-03,
       -5.9481682e-03, -3.1574708e-03,  8.7218201e-03, -8.7749623e-03,
        4.7492050e-03,  2.2580377e-03, -5.2091195e-03, -8.0746105e-03,
        1.7492552e-03,  2.3785022e-03, -3.5052754e-03, -4.6998593e-05,
        2.9138213e-03,  4.9382113e-03,  9.0211444e-03,  3.2469854e-04,
        9.1154939e-03,  9.9053178e-03,  5.9981453e-03,  1.4483436e-03,
       -4.9870722e-03,  7.3788292e-03,  8.8976519e-03,  9.5242197e-03,
       -8.0142850e-03, -3.1874701e-03, -9.7227696e-04,  9.0022869e-03,
       -3.2567875e-03, -4.1556978e-03,  6.7192935e-03,  6.3397776e-04,
        6.9945310e-03, -1.5234686e-03], dtype=float32)

In [17]:
model['users']

/home/garycc227/.venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([ 0.00884899, -0.00543833, -0.00075133, -0.00929632,  0.00438422,
        0.0041352 , -0.00615141,  0.00186839, -0.00016059, -0.00251182,
       -0.00431789,  0.00433978,  0.00822437,  0.0018765 ,  0.0039946 ,
        0.00600748, -0.00303829, -0.00783999,  0.00472586,  0.00542014,
        0.00414423, -0.00691766,  0.00026773,  0.00011057,  0.00884471,
        0.00689606, -0.0026408 , -0.00269081,  0.00435975,  0.00242714,
        0.00665418, -0.00295161,  0.00987958, -0.00745085, -0.00889334,
        0.00108802,  0.00675798,  0.00383092, -0.00949412, -0.00883584,
        0.00574724, -0.00512905,  0.00166094,  0.00744863,  0.00343533,
       -0.00872492,  0.00050036,  0.00212968,  0.00818122,  0.0010082 ],
      dtype=float32)

In [18]:
model.wv.most_similar('users')

[('answers', 0.35855695605278015),
 ('single-screen', 0.3249632716178894),
 ('levels', 0.310737669467926),
 ('performers', 0.3002103567123413),
 ('solutions', 0.2951067090034485),
 ('relational', 0.2926594316959381),
 ('Illinois', 0.2840318977832794),
 ('accomplishment', 0.28236401081085205),
 ('conclude', 0.2821692228317261),
 ('Museum', 0.2755274772644043)]

In [19]:
    # save model
model.save('model.bin')
    # load model
new_model = Word2Vec.load('model.bin')
print(new_model)

Word2Vec(vocab=661, size=50, alpha=0.025)


In [20]:
my_dict=dict({})
for idx,key in enumerate(model.wv.vocab):
    my_dict[key] = model.wv[key]


In [40]:
%store my_dict > filename.txt

Writing 'my_dict' (dict) to file 'filename.txt'.


In [173]:

pd.DataFrame(model[sentence[0]]).to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output011.csv', header=None, index=None)

D:\anaconda\New folder\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


NameError: name 'arr' is not defined

In [217]:
for i in range (0,11):
    vectorxx=model[sentences[i]]
    print (vectorxx)
    i=i+1
#pd.DataFrame(vectorxx).to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6767records/outputxx.csv', header=None, index=None)



[[ 0.00522192  0.00464929  0.00637242 ...  0.0046344  -0.00926877
  -0.00964397]
 [-0.00959601 -0.00887549  0.00726755 ... -0.00141995 -0.00031487
   0.00936592]
 [ 0.00617066 -0.00242746 -0.00263546 ... -0.00705021 -0.00284521
  -0.00726714]
 ...
 [-0.00596212 -0.00905854 -0.00165414 ...  0.00734542 -0.00332969
   0.00022466]
 [-0.00858249  0.00480558  0.00175526 ...  0.00358897 -0.00723717
   0.00728063]
 [-0.00272801  0.01025011  0.00869508 ... -0.0064599   0.01308143
   0.00735428]]
[[ 0.00054198  0.00148743 -0.00173265 ...  0.00319204 -0.00303712
  -0.00622256]
 [ 0.00292121 -0.00124108  0.00412764 ... -0.00691221  0.00177722
   0.00289971]
 [-0.0054913  -0.00128075  0.00397847 ... -0.00917341 -0.00776393
  -0.00910064]
 ...
 [-0.00274964  0.00632355  0.00427716 ...  0.00867445  0.00730605
  -0.00372841]
 [ 0.00745614  0.0044686  -0.00272306 ...  0.00406184 -0.00640668
  -0.0065537 ]
 [-0.00272801  0.01025011  0.00869508 ... -0.0064599   0.01308143
   0.00735428]]
[[ 0.00054198  0

D:\anaconda\New folder\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


IndexError: list index out of range

In [143]:
len(vectorxx)

269

In [148]:
len(sentences[9])

138

In [322]:

import csv 
f = open('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output011.csv','w') 
with f:    
    writer = csv.writer(f)
    #for i in model[sentences[i]]:
    for i in range (0,10):
        writer.writerows(model.wv[sentences[i]])
        print (i)
        
    #pd.DataFrame(model.wv[sentences[i]]).to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output000.csv', header=None, index=None)     
    #print(model.wv[sentences[i]])
        #writer.writerows(row)
        #print(sentences[i])
        #for g in sentences[i]:
                #vectorg=model[g]
                #vectorg
        #print (model[sentences[i]])
        #print(len(model[sentences[i]]))
        
        #writer.writerow(i)
        #print (sentences[i])
        #print(i)
        

0
1
2
3
4
5
6
7
8
9


In [316]:
for i in range (0,10):
    print (i)
    pd.DataFrame(model.wv[sentences[i]]).to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output000.csv', header=None, index=None)     
    print(model.wv[sentences[i]])
    

0
1
2
3
4
5
6
7
8
9


In [315]:
len(sentences[9])

            


138

In [262]:
for b in dataS0:
    vector0=model.wv[b]
    print(b)
vector0

Users
interact
with
museum
application
interfaces
for
many
reasons
.
There
are
various
types
of
users
,
who
want
to
perform
various
tasks
,
in
various
contexts
,
that
can
access
the
same
Web
site
.
Thus
,
it
is
important
to
have
user
interfaces
able
to
adapt
to
these
different
user
requirements
to
facilitate
the
accomplishment
of
the
desired
goals
.
Most
current
interfaces
to
museum
information
do
not
take
into
account
this
variety
of
types
of
users
,
thus
providing
interfaces
that
some
users
find
confusing
to
achieve
their
goals
.
In
this
article
we
discuss
the
various
possible
levels
of
support
that
can
be
given
to
different
users
during
navigation
of
museum
information
.
In
particular
,
we
focus
our
attention
on
how
to
obtain
adaptable
and
adaptive
interfaces
using
the
web
site
for
the
Marble
Museum
,
which
we
have
designed
and
developed
,
as
a
source
of
examples
for
our
discussion
of
possible
solutions
.


array([-0.00272801,  0.01025011,  0.00869508, -0.00603152, -0.00234998,
        0.0024737 ,  0.00629046,  0.00603006, -0.00197131,  0.00790817,
        0.00832713,  0.00050472,  0.00839558, -0.0050796 , -0.00120804,
        0.00798003, -0.0032761 , -0.00236395, -0.00846815,  0.00261839,
        0.00575379, -0.00663343,  0.00125535, -0.00956227, -0.00352249,
       -0.00712695,  0.00496357,  0.00667401, -0.00323298, -0.01089647,
       -0.00860629, -0.00156536,  0.00189181, -0.00324027,  0.00560648,
        0.00283529, -0.00261548, -0.00595194, -0.00292998,  0.00450147,
        0.00493084, -0.01356676, -0.00956466, -0.00273291,  0.00761357,
        0.0005826 , -0.00355414, -0.0064599 ,  0.01308143,  0.00735428],
      dtype=float32)

In [108]:
import numpy
model[sentence[1]]
numpy.savetext('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output011.csv',model[sentence[1]],newline=" ")

D:\anaconda\New folder\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


AttributeError: module 'numpy' has no attribute 'savetext'

In [10]:
len(model[model.wv.vocab])

D:\anaconda\New folder\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


661

In [11]:
model[model.wv.vocab]

D:\anaconda\New folder\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([[ 0.0065197 ,  0.00649204, -0.00461958, ..., -0.00286978,
         0.00869694, -0.00946924],
       [-0.00811216,  0.00493984,  0.00117877, ...,  0.00697611,
        -0.00796127,  0.00737014],
       [-0.00600113,  0.00782244, -0.00043111, ..., -0.00023677,
         0.00855855, -0.00967756],
       ...,
       [-0.00162842, -0.00704718, -0.00980988, ..., -0.00949891,
         0.00053812, -0.00414454],
       [ 0.00253332, -0.00766414, -0.00503861, ..., -0.00477394,
         0.00309421,  0.00723839],
       [-0.0029386 , -0.00594744, -0.0009754 , ...,  0.00388332,
        -0.00087739, -0.0037031 ]], dtype=float32)

In [12]:
 pd.DataFrame(model[model.wv.vocab]).to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output000.csv', header=None, index=None)     

D:\anaconda\New folder\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.
