In [1]:
import pandas as pd
import numpy as np
import gensim, logging
from gensim.models import Word2Vec
import nltk
nltk.download('punkt')
data= pd.read_excel('C:/Users/Owen Ou/Desktop/work_vectors/6767records/6767test.xlsx')
newdata=data['context'].values
sentences = [nltk.word_tokenize(context) for context in newdata]
    # train model
model = Word2Vec(sentences, min_count=1,size=50)
    # summarize the loaded model
print(model)
sentences
#len(sentences) #10
#len(sentences[9]) #138

D:\anaconda\New folder\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


[nltk_data] Downloading package punkt to C:\Users\Owen
[nltk_data]     Ou\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Word2Vec(vocab=661, size=50, alpha=0.025)


[['Users',
  'interact',
  'with',
  'museum',
  'application',
  'interfaces',
  'for',
  'many',
  'reasons',
  '.',
  'There',
  'are',
  'various',
  'types',
  'of',
  'users',
  ',',
  'who',
  'want',
  'to',
  'perform',
  'various',
  'tasks',
  ',',
  'in',
  'various',
  'contexts',
  ',',
  'that',
  'can',
  'access',
  'the',
  'same',
  'Web',
  'site',
  '.',
  'Thus',
  ',',
  'it',
  'is',
  'important',
  'to',
  'have',
  'user',
  'interfaces',
  'able',
  'to',
  'adapt',
  'to',
  'these',
  'different',
  'user',
  'requirements',
  'to',
  'facilitate',
  'the',
  'accomplishment',
  'of',
  'the',
  'desired',
  'goals',
  '.',
  'Most',
  'current',
  'interfaces',
  'to',
  'museum',
  'information',
  'do',
  'not',
  'take',
  'into',
  'account',
  'this',
  'variety',
  'of',
  'types',
  'of',
  'users',
  ',',
  'thus',
  'providing',
  'interfaces',
  'that',
  'some',
  'users',
  'find',
  'confusing',
  'to',
  'achieve',
  'their',
  'goals',
  '.

In [3]:
    # summarize vocabulary
words = list(model.wv.vocab)
print(words)
len(words)

['Users', 'interact', 'with', 'museum', 'application', 'interfaces', 'for', 'many', 'reasons', '.', 'There', 'are', 'various', 'types', 'of', 'users', ',', 'who', 'want', 'to', 'perform', 'tasks', 'in', 'contexts', 'that', 'can', 'access', 'the', 'same', 'Web', 'site', 'Thus', 'it', 'is', 'important', 'have', 'user', 'able', 'adapt', 'these', 'different', 'requirements', 'facilitate', 'accomplishment', 'desired', 'goals', 'Most', 'current', 'information', 'do', 'not', 'take', 'into', 'account', 'this', 'variety', 'thus', 'providing', 'some', 'find', 'confusing', 'achieve', 'their', 'In', 'article', 'we', 'discuss', 'possible', 'levels', 'support', 'be', 'given', 'during', 'navigation', 'particular', 'focus', 'our', 'attention', 'on', 'how', 'obtain', 'adaptable', 'and', 'adaptive', 'using', 'web', 'Marble', 'Museum', 'which', 'designed', 'developed', 'as', 'a', 'source', 'examples', 'discussion', 'solutions', 'This', 'begins', 'by', 'presenting', 'discussing', 'distinction', 'between',

661

In [4]:
#model.most_similar('rules')

    # access vector for one word
#print(model.wv)
model.wv
#model.most_similar('rules').to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output.csv',index = None, header=False)

    # save model
#model.save('model.bin')
    # load model
#new_model = Word2Vec.load('model.bin')
#print(new_model)

In [32]:
for a in sentences:
    vector=model.wv[a]
vector

TypeError: list indices must be integers or slices, not list

In [36]:
for i in range(0, 10):
    vectoraa=model.wv[sentences[8]]
vectoraa

#pd.DataFrame(vectoraa).to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output08.csv', header=None, index=None)
len(sentences[8])


269

In [244]:
dataS0=sentences[0]
dataS0

['Users',
 'interact',
 'with',
 'museum',
 'application',
 'interfaces',
 'for',
 'many',
 'reasons',
 '.',
 'There',
 'are',
 'various',
 'types',
 'of',
 'users',
 ',',
 'who',
 'want',
 'to',
 'perform',
 'various',
 'tasks',
 ',',
 'in',
 'various',
 'contexts',
 ',',
 'that',
 'can',
 'access',
 'the',
 'same',
 'Web',
 'site',
 '.',
 'Thus',
 ',',
 'it',
 'is',
 'important',
 'to',
 'have',
 'user',
 'interfaces',
 'able',
 'to',
 'adapt',
 'to',
 'these',
 'different',
 'user',
 'requirements',
 'to',
 'facilitate',
 'the',
 'accomplishment',
 'of',
 'the',
 'desired',
 'goals',
 '.',
 'Most',
 'current',
 'interfaces',
 'to',
 'museum',
 'information',
 'do',
 'not',
 'take',
 'into',
 'account',
 'this',
 'variety',
 'of',
 'types',
 'of',
 'users',
 ',',
 'thus',
 'providing',
 'interfaces',
 'that',
 'some',
 'users',
 'find',
 'confusing',
 'to',
 'achieve',
 'their',
 'goals',
 '.',
 'In',
 'this',
 'article',
 'we',
 'discuss',
 'the',
 'various',
 'possible',
 'levels',

In [245]:
for b in dataS0:
    vector0=model.wv[b]
vector0
#len(vector4) #138

array([-0.00272801,  0.01025011,  0.00869508, -0.00603152, -0.00234998,
        0.0024737 ,  0.00629046,  0.00603006, -0.00197131,  0.00790817,
        0.00832713,  0.00050472,  0.00839558, -0.0050796 , -0.00120804,
        0.00798003, -0.0032761 , -0.00236395, -0.00846815,  0.00261839,
        0.00575379, -0.00663343,  0.00125535, -0.00956227, -0.00352249,
       -0.00712695,  0.00496357,  0.00667401, -0.00323298, -0.01089647,
       -0.00860629, -0.00156536,  0.00189181, -0.00324027,  0.00560648,
        0.00283529, -0.00261548, -0.00595194, -0.00292998,  0.00450147,
        0.00493084, -0.01356676, -0.00956466, -0.00273291,  0.00761357,
        0.0005826 , -0.00355414, -0.0064599 ,  0.01308143,  0.00735428],
      dtype=float32)

In [18]:
pd.DataFrame(vector).to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output.csv', header=None, index=None)
#pd.DataFrame(model.wv).to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6|767records/output01.csv', header=None, index=None)

In [226]:
for a in words:
    vector_2=model.wv[a]
vector_2


array([-4.3851417e-03, -1.5982499e-03, -4.7484157e-03, -6.0286415e-03,
        4.9928082e-03, -8.7339580e-03,  6.8261898e-03, -6.9253203e-03,
        1.1664722e-03,  1.7147429e-03,  6.8486878e-03, -4.1668667e-03,
        1.8966330e-05, -1.6488323e-03,  3.2077011e-04, -1.5775668e-03,
       -4.5429925e-03,  4.7321138e-03,  2.6537138e-03, -2.3333703e-03,
       -7.0141879e-04,  8.1702613e-04, -7.3270192e-03, -6.8790494e-03,
        1.4695926e-03,  9.1027953e-03, -1.2809503e-03, -8.9310678e-03,
        6.2160539e-03, -4.7065903e-04, -2.6264021e-03, -3.3121950e-03,
       -4.5056916e-03, -7.1702663e-05,  5.3022736e-06,  9.1603259e-03,
       -4.1383738e-03, -4.5656441e-03,  6.6355243e-03,  8.0908798e-03,
       -6.3040913e-03, -4.6107788e-03, -7.2777951e-03,  6.0251458e-03,
        8.9322859e-03, -9.2464685e-03,  7.2650233e-04, -1.7103208e-03,
        7.5789355e-03,  7.0694224e-03], dtype=float32)

In [41]:
model['users']

D:\anaconda\New folder\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([-0.00920605, -0.00165002,  0.00931641,  0.00271723,  0.00124727,
       -0.00984887, -0.00488263,  0.00563136, -0.00201676, -0.00825968,
       -0.00111113,  0.00121327,  0.00388812, -0.00530687,  0.00653256,
       -0.00587977, -0.0019659 ,  0.00340984, -0.00550252,  0.00240596,
       -0.00073841, -0.00225373,  0.00300271,  0.00775542, -0.00186058,
        0.00160715, -0.00793876,  0.00582501, -0.0018391 , -0.01082551,
        0.00720843, -0.00274383, -0.00396364,  0.00726024, -0.00592281,
        0.0074455 ,  0.00831207,  0.00767825,  0.0053503 ,  0.00777281,
        0.00102251, -0.00032086, -0.00368132, -0.00223245,  0.00648672,
       -0.00901596, -0.00065545,  0.00161241, -0.00575947,  0.00102181],
      dtype=float32)

In [16]:
model.wv.most_similar('users')

[('virtual', 0.38336634635925293),
 ('selected', 0.36117106676101685),
 ('data', 0.339395672082901),
 ('middle', 0.3376902937889099),
 ('review', 0.3342435956001282),
 ('author', 0.3317137360572815),
 ('discuss', 0.3247452974319458),
 ('asynchronous', 0.3197464346885681),
 ('(', 0.31894469261169434),
 ('independence', 0.310139536857605)]

In [20]:
    # save model
model.save('model.bin')
    # load model
new_model = Word2Vec.load('model.bin')
print(new_model)

Word2Vec(vocab=661, size=50, alpha=0.025)


In [39]:
my_dict=dict({})
for idx,key in enumerate(model.wv.vocab):
    my_dict[key] = model.wv[key]


array([-4.3851417e-03, -1.5982499e-03, -4.7484157e-03, -6.0286415e-03,
        4.9928082e-03, -8.7339580e-03,  6.8261898e-03, -6.9253203e-03,
        1.1664722e-03,  1.7147429e-03,  6.8486878e-03, -4.1668667e-03,
        1.8966330e-05, -1.6488323e-03,  3.2077011e-04, -1.5775668e-03,
       -4.5429925e-03,  4.7321138e-03,  2.6537138e-03, -2.3333703e-03,
       -7.0141879e-04,  8.1702613e-04, -7.3270192e-03, -6.8790494e-03,
        1.4695926e-03,  9.1027953e-03, -1.2809503e-03, -8.9310678e-03,
        6.2160539e-03, -4.7065903e-04, -2.6264021e-03, -3.3121950e-03,
       -4.5056916e-03, -7.1702663e-05,  5.3022736e-06,  9.1603259e-03,
       -4.1383738e-03, -4.5656441e-03,  6.6355243e-03,  8.0908798e-03,
       -6.3040913e-03, -4.6107788e-03, -7.2777951e-03,  6.0251458e-03,
        8.9322859e-03, -9.2464685e-03,  7.2650233e-04, -1.7103208e-03,
        7.5789355e-03,  7.0694224e-03], dtype=float32)

In [40]:
%store my_dict > filename.txt

Writing 'my_dict' (dict) to file 'filename.txt'.


In [173]:

pd.DataFrame(model[sentence[0]]).to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output011.csv', header=None, index=None)

D:\anaconda\New folder\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


NameError: name 'arr' is not defined

In [217]:
for i in range (0,11):
    vectorxx=model[sentences[i]]
    print (vectorxx)
    i=i+1
#pd.DataFrame(vectorxx).to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6767records/outputxx.csv', header=None, index=None)



[[ 0.00522192  0.00464929  0.00637242 ...  0.0046344  -0.00926877
  -0.00964397]
 [-0.00959601 -0.00887549  0.00726755 ... -0.00141995 -0.00031487
   0.00936592]
 [ 0.00617066 -0.00242746 -0.00263546 ... -0.00705021 -0.00284521
  -0.00726714]
 ...
 [-0.00596212 -0.00905854 -0.00165414 ...  0.00734542 -0.00332969
   0.00022466]
 [-0.00858249  0.00480558  0.00175526 ...  0.00358897 -0.00723717
   0.00728063]
 [-0.00272801  0.01025011  0.00869508 ... -0.0064599   0.01308143
   0.00735428]]
[[ 0.00054198  0.00148743 -0.00173265 ...  0.00319204 -0.00303712
  -0.00622256]
 [ 0.00292121 -0.00124108  0.00412764 ... -0.00691221  0.00177722
   0.00289971]
 [-0.0054913  -0.00128075  0.00397847 ... -0.00917341 -0.00776393
  -0.00910064]
 ...
 [-0.00274964  0.00632355  0.00427716 ...  0.00867445  0.00730605
  -0.00372841]
 [ 0.00745614  0.0044686  -0.00272306 ...  0.00406184 -0.00640668
  -0.0065537 ]
 [-0.00272801  0.01025011  0.00869508 ... -0.0064599   0.01308143
   0.00735428]]
[[ 0.00054198  0

D:\anaconda\New folder\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


IndexError: list index out of range

In [143]:
len(vectorxx)

269

In [148]:
len(sentences[9])

138

In [322]:

import csv 
f = open('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output011.csv','w') 
with f:    
    writer = csv.writer(f)
    #for i in model[sentences[i]]:
    for i in range (0,10):
        writer.writerows(model.wv[sentences[i]])
        print (i)
        
    #pd.DataFrame(model.wv[sentences[i]]).to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output000.csv', header=None, index=None)     
    #print(model.wv[sentences[i]])
        #writer.writerows(row)
        #print(sentences[i])
        #for g in sentences[i]:
                #vectorg=model[g]
                #vectorg
        #print (model[sentences[i]])
        #print(len(model[sentences[i]]))
        
        #writer.writerow(i)
        #print (sentences[i])
        #print(i)
        

0
1
2
3
4
5
6
7
8
9


In [316]:
for i in range (0,10):
    print (i)
    pd.DataFrame(model.wv[sentences[i]]).to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output000.csv', header=None, index=None)     
    print(model.wv[sentences[i]])
    

0
1
2
3
4
5
6
7
8
9


In [315]:
len(sentences[9])

            


138

In [262]:
for b in dataS0:
    vector0=model.wv[b]
    print(b)
vector0

Users
interact
with
museum
application
interfaces
for
many
reasons
.
There
are
various
types
of
users
,
who
want
to
perform
various
tasks
,
in
various
contexts
,
that
can
access
the
same
Web
site
.
Thus
,
it
is
important
to
have
user
interfaces
able
to
adapt
to
these
different
user
requirements
to
facilitate
the
accomplishment
of
the
desired
goals
.
Most
current
interfaces
to
museum
information
do
not
take
into
account
this
variety
of
types
of
users
,
thus
providing
interfaces
that
some
users
find
confusing
to
achieve
their
goals
.
In
this
article
we
discuss
the
various
possible
levels
of
support
that
can
be
given
to
different
users
during
navigation
of
museum
information
.
In
particular
,
we
focus
our
attention
on
how
to
obtain
adaptable
and
adaptive
interfaces
using
the
web
site
for
the
Marble
Museum
,
which
we
have
designed
and
developed
,
as
a
source
of
examples
for
our
discussion
of
possible
solutions
.


array([-0.00272801,  0.01025011,  0.00869508, -0.00603152, -0.00234998,
        0.0024737 ,  0.00629046,  0.00603006, -0.00197131,  0.00790817,
        0.00832713,  0.00050472,  0.00839558, -0.0050796 , -0.00120804,
        0.00798003, -0.0032761 , -0.00236395, -0.00846815,  0.00261839,
        0.00575379, -0.00663343,  0.00125535, -0.00956227, -0.00352249,
       -0.00712695,  0.00496357,  0.00667401, -0.00323298, -0.01089647,
       -0.00860629, -0.00156536,  0.00189181, -0.00324027,  0.00560648,
        0.00283529, -0.00261548, -0.00595194, -0.00292998,  0.00450147,
        0.00493084, -0.01356676, -0.00956466, -0.00273291,  0.00761357,
        0.0005826 , -0.00355414, -0.0064599 ,  0.01308143,  0.00735428],
      dtype=float32)

In [108]:
import numpy
model[sentence[1]]
numpy.savetext('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output011.csv',model[sentence[1]],newline=" ")

D:\anaconda\New folder\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


AttributeError: module 'numpy' has no attribute 'savetext'

In [10]:
len(model[model.wv.vocab])

D:\anaconda\New folder\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


661

In [11]:
model[model.wv.vocab]

D:\anaconda\New folder\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([[ 0.0065197 ,  0.00649204, -0.00461958, ..., -0.00286978,
         0.00869694, -0.00946924],
       [-0.00811216,  0.00493984,  0.00117877, ...,  0.00697611,
        -0.00796127,  0.00737014],
       [-0.00600113,  0.00782244, -0.00043111, ..., -0.00023677,
         0.00855855, -0.00967756],
       ...,
       [-0.00162842, -0.00704718, -0.00980988, ..., -0.00949891,
         0.00053812, -0.00414454],
       [ 0.00253332, -0.00766414, -0.00503861, ..., -0.00477394,
         0.00309421,  0.00723839],
       [-0.0029386 , -0.00594744, -0.0009754 , ...,  0.00388332,
        -0.00087739, -0.0037031 ]], dtype=float32)

In [12]:
 pd.DataFrame(model[model.wv.vocab]).to_csv('C:/Users/Owen Ou/Desktop/work_vectors/6767records/output000.csv', header=None, index=None)     

D:\anaconda\New folder\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.
